FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY . .
COPY nginx.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s   CMD wget -qO- http://localhost/ >/dev/null || exit 1
